### ISSUE TITLE
Replace inconsistent _instX implementation by a pattern based system

### ISSUE THREAD

**Issue by jclaveau** [jclaveau/ansible-vagrant-modules#21]
```yaml
vagrant:
  cmd: up
  vm_name: frank_%d
  count: 8

vagrant:
  cmd: halt
  vm_name: frank_\d+
  vm_name: frank_(0|3|8)
```

https://pytutorial.com/python-variable-in-string
