### ISSUE TITLE
Support a network entry

### ISSUE THREAD

**Issue by jclaveau** [jclaveau/ansible-vagrant-modules#48]
```yaml
network:
 - - public_network
   - ip: x.x.x.x
     type: dhcp
     bridge: ...
 - - private_network
   - ip: x.x.x.x
     netmask: x.x.x.x
     :libvirt__network_name: my_network
```
